# Site settings
title: Yiting Liu - Creative Technologist  
email: yiting@yitingliu.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Yiting's playground where I focus on AR/VR, web, and music. 
  I am a creative technologist designing experiences to foster meaningful 
  interactions through AR/VR, music, and performance.
# baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "https://www.yitingliu.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Yitingliu97
instagram_username: yliu.designs
linkedin_username: yitingliu97
soundcloud_username: yitingliu
# Build settings
markdown: kramdown
permalink: none

kramdown:
  input: GFM    
  # auto_ids: true

plugins:
  - jekyll-archives